server:
    port: 8051
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    security:
        user:
            name: admin
            password: 1234
    application:
        name: streaming-service
    datasource:
        url: jdbc:postgresql://localhost:5432/flix-streaming
        username: dydwls140
        password: "@astems1027"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            # ddl-auto: update # 애플리케이션 시작 시 데이터베이스 스키마를 자동 업데이트합니다.
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: never
    devtools:
        restart:
            enabled: true

    data:
        redis:
            host: localhost
            port: 6379
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: streaming-service
