server:
    port: 8050
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    security:
        user:
            name: admin
            password: 1234
    application:
        name: streaming-service
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.postgresql.Driver
        # driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update # 애플리케이션 시작 시 데이터베이스 스키마를 자동 업데이트합니다.
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

    data:
        redis:
            host: localhost
            port: 6379
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id:
                streaming-service: streaming-service
